---
accept_established:
  action: accept
  state:
    established: true

accept_related:
  action: accept
  state:
    related: true

drop_invalid:
  action: drop
  state:
    invalid: true

accept_icmp:
  action: accept
  protocol: icmp

accept_igmp:
  action: accept
  protocol: 2

accept_dns:
  action: accept
  protocol: tcp_udp
  destination:
    port: domain,domain-s

accept_bgp:
  action: accept
  protocol: tcp
  destination:
    port: bgp

accept_ssh:
  action: accept
  protocol: tcp
  destination:
    port: ssh

accept_http:
  action: accept
  protocol: tcp
  destination:
    port: http

accept_https:
  action: accept
  protocol: tcp
  destination:
    port: https

accept_ntp:
  action: accept
  protocol: udp
  destination:
    port: ntp

accept_dhcp:
  action: accept
  protocol: udp
  source:
    port: 67,68
  destination:
    port: 67,68

accept_mdns:
  action: accept
  protocol: udp
  source:
    port: mdns
  destination:
    port: mdns

accept_vyos_coredns:
  protocol: tcp_udp
  destination:
    port: domain,domain-s
    address-group: vyos_coredns

accept_wireguard:
  action: accept
  protocol: udp
  destination:
    port: 51820

accept_tftp:
  action: accept
  protocol: udp
  destination:
    port: 69

accept_k8s_api:
  action: accept
  protocol: tcp
  destination:
    port: 6443

accept_ingress_from_cloudflare:
  action: accept
  protocol: tcp
  source:
    network-group: cloudflare-ipv4
  destination:
    port: http,https
    address-group: k8s_ingress

accept_mqtt_from_mqtt_clients:
  action: accept
  protocol: tcp
  source:
    address-group: mqtt_clients
  destination:
    port: 1883
    address-group: k8s_mqtt

accept_k8s_nodes:
  action: accept
  protocol: tcp
  source:
    address-group: k8s_nodes

accept_prometheus_from_k8s_nodes:
  action: accept
  protocol: tcp
  source:
    address-group: k8s_nodes
  destination:
    port: 9153

accept_jellyfin_from_jellyfin_clients:
  action: accept
  protocol: tcp
  source:
    address-group: jellyfin_clients
  destination:
    port: 8096
    address-group: k8s_jellyfin

accept_k8s_ingress_from_allowed_devices:
  action: accept
  protocol: tcp
  source:
    address-group: k8s_ingress_allowed
  destination:
    port: http,https
    address-group: k8s_ingress

accept_k8s_ingress_from_ereaders:
  action: accept
  protocol: tcp
  source:
    address-group: ereaders
  destination:
    port: http,https
    address-group: k8s_ingress

accept_nas_smb_from_scanners:
  action: accept
  protocol: tcp
  source:
    address-group: scanners
  destination:
    port: microsoft-ds
    address-group: nas

accept_vyos_api:
  action: accept
  protocol: tcp
  destination:
    port: 8443
