---
config:
  domain_name: "private.greyrock.io"
  ntp_servers: "chronos.private.greyrock.io,0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org,3.pool.ntp.org"

  zones:
    local:
      description: Local router zone
      local_zone: true
      firewall:
        default:
          default: drop
          rules:
            - accept_ntp: null
            - accept_dhcp: null
        fromZones:
          - zones:
              - lan
            default: drop
            rules:
              - accept_ssh: null
              - accept_ntp: null
              - accept_dhcp: null
          - zones:
              - trusted
              - wg_trusted
            default: drop
            rules:
              - accept_icmp: null
              - accept_ssh: null
              - accept_ntp: null
              - accept_dhcp: null
              - accept_igmp: null
              - accept_mdns: null
              - accept_vyos_api: null
          - zones:
              - iot
            default: drop
            rules:
              - accept_ssh: null
              - accept_ntp: null
              - accept_dhcp: null
              - accept_igmp: null
              - accept_mdns: null
          - zones:
              - servers
            default: drop
            rules:
              - accept_icmp: null
              - accept_ntp: null
              - accept_dhcp: null
              - accept_bgp: null
              - accept_tftp: null
              - accept_prometheus_from_k8s_nodes: null
              - accept_mdns: null
          - zones:
              - wan
            default: drop
            rules:
              - accept_wireguard: null
          - zones:
              - guest
            default: drop
            rules:
              - accept_dhcp: null

    wan:
      interface: eth4
      firewall:
        default:
          default: accept
          defaultLog: false
          rules: []
        fromZones:
          - zones:
              - video
            default: drop
            defaultLog: false
            rules: []

    lan:
      interface: eth5
      dhcp:
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []

        fromZones:
          - zones:
              - trusted
              - wg_trusted
            default: accept
            defaultLog: false
            rules: []
          - zones:
              - servers
            default: drop
            defaultLog: false
            rules:
              - accept_icmp: null

    rescue:
      interface: eth6
      dhcp:
        name_server: ${cidrhost(networks["rescue"], 1)}

    servers:
      interface: eth5.10
      dhcp:
        domain_name: private.greyrock.io
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []

        fromZones:
          - zones:
              - trusted
              - wg_trusted
              - services
            default: accept
            defaultLog: false
            rules:
              - accept_icmp: null
          - zones:
              - wan
            default: drop
            rules:
              - accept_ingress_from_cloudflare: null
          - zones:
              - lan
            default: drop
            rules:
              - accept_icmp: null
          - zones:
              - iot
            default: drop
            rules:
              - accept_nas_smb_from_scanners: null
              - accept_plex_from_plex_clients: null
              - accept_jellyfin_from_jellyfin_clients: null
              - accept_mqtt_from_mqtt_clients: null
              - accept_k8s_ingress_from_ereaders: null
              - accept_k8s_ingress_from_allowed_devices: null
              - accept_awnet_from_weather_stations: null
          - zones:
              - local
            default: drop
            rules:
              - accept_bgp: null
              - accept_k8s_api: null
              - accept_dns: null
              - accept_ntp: null
              - accept_mdns: null

    trusted:
      interface: eth5.20
      dhcp:
        domain_name: private.greyrock.io
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []
        fromZones:
          - zones:
              - local
            default: drop
            rules:
              - accept_igmp: null
              - accept_mdns: null
          - zones:
              - wg_trusted
            default: accept
            defaultLog: false
            rules: []
          - zones:
              - iot
            default: drop
            rules: []
          - zones:
              - servers
            default: drop
            defaultLog: false
            rules:
              - accept_icmp: null

    guest:
      interface: eth5.30
      dhcp:
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []

    iot:
      interface: eth5.40
      dhcp:
        domain_name: private.greyrock.io
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []
        fromZones:
          - zones:
              - trusted
              - wg_trusted
            default: accept
            defaultLog: false
            rules:
              - accept_icmp: null
          - zones:
              - servers
            default: drop
            rules:
              - accept_icmp: null
              - accept_k8s_nodes: null
          - zones:
              - local
            default: drop
            rules:
              - accept_igmp: null
              - accept_mdns: null
          - zones:
              - guest
            default: drop
            rules: []

    video:
      interface: eth5.50
      dhcp:
        domain_name: private.greyrock.io
        name_server: ${address_book.services.vyos_dnsdist.ipv4_addr}
      firewall:
        default:
          default: drop
          rules: []
        fromZones:
          - zones:
              - trusted
              - wg_trusted
            default: accept
            defaultLog: false
            rules:
              - accept_icmp: null
          - zones:
              - servers
            default: drop
            rules:
              - accept_icmp: null
              - accept_k8s_nodes: null

    wg_trusted:
      interface: wg01
      port: 51820
      peers:
        iphone-todd:
          ipv4_hostid: 2
          public_key: Nra9xTkUYNynIZvjAurDkYDaDOSVeb/COgmzcxRmHio=
        ipad-todd:
          ipv4_hostid: 3
          public_key: tyxACMBFCXxJZ8AdrHfXAI+lhueC7Msrj0s/DCNnXgs=
        macbook-todd:
          ipv4_hostid: 4
          public_key: /NCWOUGrjcspzfwMraFKHUu40lXbxX0Rt7baosoM+Do=
      firewall:
        default:
          default: drop
          rules: []

        fromZones:
          - zones:
              - local
            default: drop
            rules:
              - accept_igmp: null
              - accept_mdns: null
          - zones:
              - iot
            default: drop
            rules: []

    services:
      description: VyOS services zone
      interface: cni-services
      firewall:
        default:
          default: accept
          defaultLog: false
          rules:
            - accept_dns: null
        fromZones:
          - zones:
              - servers
            default: accept
            rules:
              - accept_dns: null
              - accept_k8s_api: null
          - zones:
              - guest
            default: drop
            rules:
              - accept_dns: null
          - zones:
              - wan
            default: drop
            rules: []

  nat:
    destination:
      - description: HTTPS
        protocol: tcp
        interface: wan
        port: 443
        address: ${address_book.services.k8s_ingress.ipv4_addr}
      - description: HTTP
        protocol: tcp
        interface: wan
        port: 80
        address: ${address_book.services.k8s_ingress.ipv4_addr}
      - description: Force DNS for IoT
        port: 53
        protocol: tcp_udp
        interface: iot
        destinationAddress: "!${address_book.services.vyos_dnsdist.ipv4_addr}"
        address: ${address_book.services.vyos_dnsdist.ipv4_addr}
      - description: Force DNS for Video
        port: 53
        protocol: tcp_udp
        interface: video
        destinationAddress: "!${address_book.services.vyos_dnsdist.ipv4_addr}"
        address: ${address_book.services.vyos_dnsdist.ipv4_addr}
      - description: Force NTP for LAN
        port: 123
        protocol: udp
        interface: lan
        destinationAddress: "!${cidrhost(networks.lan, 1)}"
        address: "${cidrhost(networks.lan, 1)}"
      - description: Force NTP for Servers
        port: 123
        protocol: udp
        interface: servers
        destinationAddress: "!${cidrhost(networks.servers, 1)}"
        address: "${cidrhost(networks.servers, 1)}"
      - description: Force NTP for Trusted
        port: 123
        protocol: udp
        interface: trusted
        destinationAddress: "!${cidrhost(networks.trusted, 1)}"
        address: "${cidrhost(networks.trusted, 1)}"
      - description: Force NTP for IoT
        port: 123
        protocol: udp
        interface: iot
        destinationAddress: "!${cidrhost(networks.iot, 1)}"
        address: "${cidrhost(networks.iot, 1)}"
      - description: Force NTP for Video
        port: 123
        protocol: udp
        interface: video
        destinationAddress: "!${cidrhost(networks.video, 1)}"
        address: "${cidrhost(networks.video, 1)}"
      - description: Force NTP for Wireguard Trusted
        port: 123
        protocol: udp
        interface: wg_trusted
        destinationAddress: "!${cidrhost(networks.wg_trusted, 1)}"
        address: "${cidrhost(networks.wg_trusted, 1)}"
