---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mosquitto-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto_pwd: |
          {{ .mosquitto_mqtt_username }}:{{ .mosquitto_mqtt_password }}
          {{ .mosquitto_zigbee2mqtt_username }}:{{ .mosquitto_zigbee2mqtt_password }}
          {{ .mosquitto_frigate_username }}:{{ .mosquitto_frigate_password }}
          {{ .mosquitto_amcrest2mqtt_courtyard_username }}:{{ .mosquitto_amcrest2mqtt_courtyard_password }}
          {{ .mosquitto_home_assistant_username }}:{{ .mosquitto_home_assistant_password }}
          {{ .mosquitto_teslamate_username }}:{{ .mosquitto_teslamate_password }}
          {{ .mosquitto_ambientweather2mqtt_username }}:{{ .mosquitto_ambientweather2mqtt_password }}
          {{ .mosquitto_rtlamr2mqtt_username }}:{{ .mosquitto_rtlamr2mqtt_password }}
          {{ .mosquitto_zwave_js_ui_username }}:{{ .mosquitto_zwave_js_ui_password }}
  dataFrom:
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
