---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onepassword-scim-scimsession
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-scim-scimsession
    creationPolicy: Owner
  data:
    - secretKey: scimsession
      remoteRef:
        key: OP-SCIM
        property: scimsession
