---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-scim
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: op-scim-bridge
      version: 2.9.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: op-scim-bridge
        namespace: flux-system

  values:
    scim:
      credentialsVolume:
        files: ""
        storageClass: ceph-block

      credentialsSecrets:
        scimsession:
          key: onepassword-scim-scimsession

      ingress:
        enabled: true
        annotations:
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host op-scim.greyrock.tech
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - *host
