---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-teslamate
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/selfhosted/teslamate/app
  sourceRef:
    kind: GitRepository
    name: greyrock-ops
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-onepassword-connect
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: teslamate
      namespace: selfhosted
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
