---
- name: Add group
  ansible.builtin.group:
    name: timemachine

- name: Add user
  ansible.builtin.user:
    name: "{{ tm_todd_laptop_user }}"
    password: '!'
    create_home: false
    groups: timemachine
    append: yes
