---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block
