---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious-server
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-server-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres database
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
        POSTGRES_USER: "{{ .invidious_server_postgres_username }}"
        POSTGRES_PASS: "{{ .invidious_server_postgres_password }}"
        POSTGRES_DB: invidious
        database_url: postgres://{{ .invidious_server_postgres_username }}:{{ .invidious_server_postgres_password }}@postgres-rw.databases.svc.cluster.local.:5432/invidious

  dataFrom:
    - extract:
        key: cloudnative-pg-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cnpg_postgres_$1"
    - extract:
        key: invidious-server
      rewrite:
        - regexp:
            source: "(.*)"
            target: "invidious_server_$1"
