---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invidious-server
  namespace: selfhosted
spec:
  interval: 15m

  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.7@sha256:63d3321053b2033bd5dff909959513939795f7ec7d66b473b457f933325c4c5a
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: invidious-server-secret

    image:
      repository: quay.io/invidious/invidious
      tag: latest@sha256:dd9c4d589678c31205c23815bef6c919f371b7e49b5cf07ec50489d51e6844c3

    envFrom:
      - secretRef:
          name: invidious-server-secret

    service:
      main:
        ports:
          http:
            port: &port 3000

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          hajimari.io/enable: "true"
          hajimari.io/instance: "todd,andy"
          hajimari.io/icon: simple-icons:youtube
        hosts:
          - host: &host 'invidious.greyrock.tech'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: invidious-server

    resources:
      requests:
        cpu: 5m
        memory: 300Mi
      limits:
        memory: 1000Mi
