---
- name: "Garage : Fetch secrets from 1Password"
  onepassword.connect.item_info:
    vault: Automation
    item: garage
  no_log: true
  register: op_item_garage

- name: "Garage : Data folder"
  ansible.builtin.file:
    path: "/tank/garage/data"
    state: directory
    group: "1000"
    owner: "1000"
    mode: '0755'

- name: "Garage : Meta folder"
  ansible.builtin.file:
    path: "/tank/garage/meta"
    state: directory
    group: "1000"
    owner: "1000"
    mode: '0755'

- name: "Garage : Manage configuration"
  become: true
  ansible.builtin.template:
    src: garage/garage.toml.j2
    dest: "/tank/garage/garage.toml"
    mode: 0644
  register: var_garage_config

- name: "Garage : Manage container"
  containers.podman.podman_container:
    name: garage
    image: "docker.io/dxflrs/garage:v0.8.1@sha256:89b8fb3d4d62e96bff2b39c35a97cf9355b01ae648e4f769f94e956622e96d61"
    state: started
    network: host
    volume:
      - "/tank/garage/meta:/var/lib/garage/meta"
      - "/tank/garage/data:/var/lib/garage/data"
      - "/tank/garage/garage.toml:/etc/garage.toml"
    env:
      TZ: "America/New_York"
    ports:
      - 3910:3910
      - 3911:3911
    generate_systemd:
      path: "/home/{{ ansible_user }}/.config/systemd/user"
      restart_policy: always
      time: 120
      names: true
      container_prefix: ansible
  become: false

- name: enable podman-systemd | garage
  ansible.builtin.systemd:
    name: ansible-garage
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  become: false
  remote_user: todd
