---
- name: Create vector directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/vector"
    - "{{ docker_base_dir }}/vector/config"
    - "{{ docker_base_dir }}/vector/data"

- name: ensure vector config
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: /home/{{ ansible_user }}/.config/vector.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: run vector
  containers.podman.podman_container:
    name: vector
    image: "docker.io/timberio/vector:0.27.0-debian@sha256:29f23dab76fa306b67b10eac3e9decdb01c906f8aa3b00a2f5b2e8ae088b84e0"
    state: started
    privileged: true
    network: host
    volume:
      - "/home/{{ ansible_user }}/.config/vector.yaml:/etc/vector/vector.yaml"
      - "/var/log:/var/log:ro"
      - "{{ docker_base_dir }}/vector:/vector-data-dir"
    command: "--config=/etc/vector/vector.yaml --watch-config"
    generate_systemd:
      path: "/home/{{ ansible_user }}/.config/systemd/user"
      restart_policy: always
      time: 120
      names: true
      container_prefix: ansible
  become: false

- name: enable podman-systemd | vector
  ansible.builtin.systemd:
    name: ansible-vector
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  become: false
