---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: selfhosted-gateway-vpnconfig
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: selfhosted-gateway-vpnconfig
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Windscribe
        property: pod_gateway_selfhosted_private_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Windscribe
        property: pod_gateway_selfhosted_addresses
    - secretKey: SERVER_HOSTNAMES
      remoteRef:
        key: Windscribe
        property: pod_gateway_selfhosted_server_hostnames
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: Windscribe
        property: pod_gateway_selfhosted_preshared_key
