---
creation_rules:
  - path_regex: k8s/(global|clusters)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93

  - path_regex: cloudflare_secret.*\.sops\.ya?ml
    age: >-
      age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93

  - path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
