---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres-v15-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
        POSTGRES_USER: "{{ .immich_postgres_username }}"
        POSTGRES_USER_FLAGS: "-s"
        POSTGRES_PASS: "{{ .immich_postgres_password }}"
        POSTGRES_DB: immich
  dataFrom:
    - extract:
        key: cloudnative-pg-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cnpg_postgres_$1"
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "immich_$1"
