---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: immich
  app.kubernetes.io/instance: immich
