---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.1.2.1532@sha256:80eb2828e3e41e3f9e20226e4cf0994e241d7547d4f0c53401d05e548f885ded

    podAnnotations:
      secret.reloader.stakater.com/reload: readarr-secrets

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      READARR__INSTANCE_NAME: Readarr
      READARR__PORT: &port 8787
      READARR__APPLICATION_URL: "https://readarr.greyrock.tech"
      READARR__LOG_LEVEL: info
      READARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: readarr-secrets
            key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.greyrock.tech/css/base/readarr/dracula.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "readarr.greyrock.tech"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: readarr-config

      media:
        enabled: true
        type: nfs
        server: "nas.private.greyrock.io"
        path: /tank/media
        mountPath: /data/nas-media

    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 1408M
