---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate-secrets
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .teslamate_encryption_key }}"
        # Postgres database
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
        POSTGRES_USER: "{{ .teslamate_postgres_username }}"
        POSTGRES_USER_FLAGS: "-s"
        POSTGRES_PASS: "{{ .teslamate_postgres_password }}"
        POSTGRES_DB: teslamate
        DATABASE_URL: postgres://{{ .teslamate_postgres_username }}:{{ .teslamate_postgres_password }}@postgres-rw.database.svc.cluster.local:5432/teslamate?sslmode=disable
        # MQTT
        MQTT_HOST: mosquitto.home-automation
        MQTT_PORT: 1883
        MQTT_USERNAME: "{{ .mosquitto_teslamate_username }}"
        MQTT_PASSWORD: "{{ .mosquitto_teslamate_password }}"
  dataFrom:
    - extract:
        key: cloudnative-pg-postgres
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cnpg_postgres_$1"
    - extract:
        key: teslamate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "teslamate_$1"
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mosquitto_$1"
