---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate-secrets
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        # Postgres database
        POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
        POSTGRES_USER: "teslamate"
        POSTGRES_USER_FLAGS: "-s"
        POSTGRESS_PASS: "{{ .POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: teslamate
