---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app teslamate
  namespace: selfhosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6@sha256:f2d6d7a172ce0c427bda01f4f68b8730b906fba96db3b34c2ec363d3693166c3
        envFrom:
          - secretRef:
              name: teslamate-secret
    controller:
      annotations:
        secret.reloader.stakater.com/reload: *app
    image:
      repository: teslamate/teslamate
      tag: 1.27.2
    podAnnotations:
      secret.reloader.stakater.com/reload: teslamate-secret
    env:
      DATABASE_HOST:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_HOST
      DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_DB
      DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_USER
      DATABASE_PASS:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_PASS
    envFrom:
      - secretRef:
          name: teslamate-secret
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 4000
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/instance: "todd"
          hajimari.io/icon: "car-electric"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "teslamate.greyrock.tech"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    postgresql:
      enabled: false
