---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app teslamate
  namespace: selfhosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6@sha256:ae3b33db2ebf7b06c0244ecc49711bcc02e89d8cebea5379ed20b59344c48372
        envFrom:
          - secretRef:
              name: teslamate-secret
    controller:
      annotations:
        secret.reloader.stakater.com/reload: *app
    image:
      repository: teslamate/teslamate
      tag: 1.27.2
    env:
      DISABLE_MQTT: "true"
      DATABASE_HOST:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_HOST
      DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_DB
      DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_USER
      DATABASE_PASS:
        valueFrom:
          secretKeyRef:
            name: teslamate-secret
            key: POSTGRES_PASS
    envFrom:
      - secretRef:
          name: teslamate-secret
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "teslamate.greyrock.tech"
            paths:
              - path: /
                pathType: Prefix
    postgresql:
      enabled: false
