---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teslamate-datasource
  namespace: selfhosted
  labels:
    grafana_datasource: "1"
data:
  ha-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: TeslaMate
      type: postgres
      access: proxy
      url: postgres-any.database.svc.cluster.local:5432
      database: teslamate
      user: teslamate
      password: $TESLAMATE_POSTGRES_PASSWORD
      jsonData:
        postgresVersion: 1000
        sslmode: disable
