apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:z9JMIwa5IKqb/f6otXDHN9XZu6qpQqaS2l4sG/Vw+7WTF/M5QTa7UB5PWXGbqTSkKv8/ocSOvtVbMu9M1n64AQTE/rgG8OG3lXbWUJhUKtKkOooDMz/UdE3DbhQeb4Y5nXOiyWZc11zYYnkXIqDCEKuW6X9TLxcvR0oSF4nw94boAdQOZFCOSsD5SV4Fvnn3E2DRww5YVPdN8415iBUF8lKo3d7SAn1wuqR032G8nyCDitaYfFpCqfg8KxUk2rWZCYAehW6oCjROm4bsrmPK8HWni6LkQ8exMlFGSXiY3QQZmwtHayxwEhbSF1MjEd4yD5EzDjVB9JBA13NdWu9uZjmOpNxPrAf8EfoCCYCcLR8QSLcwnibyFuFM75SkWa9vZgb8zO0K2ErEV4E3yYrTSS2Oq95c1GNwaTT2PEHv8xbBQE6rowssMlzk0cyA7rVgK0FSYv6EngoWxyL6iKmyHH+Sq5awqtdIFNlwidteUVMkTSdWzuf9hR6eFXaTKHHfRWwmwUERKZjfGeioBGGvx8UCirLiwxdW5THwcxU0Zi6YxO9D6H5TjzwjC0W0SvzUqJJoIBb7+ahBUjoxajGQpSLvcGzFuqRHny4A3TMLRXRZsjWBTtFNyDgCPjo0KWZyMiOqQMG+Dk9+0TU+KwHp5+mBZBj/CtTEGvgBJY2HxRHU0UMEVhDiAyvBoMp0fNUrhOlz32wq7QyHsh93heaU7rVern4plu9TPlfmo4jrTXR6T8puzjoWxiCaUvbPJvFBE5spETnPCr6ESfLs+gozKGD818ks63v0yVmTWCdUQUwSPqkW8WTa8M1ASedlFRPy8Q44CiOEHZEmF3+LI7tBM5hpsQL9HcJMTQ33U+hkfnUXH8Pwy8q9pJIeF6m9il+HeDoW8cgHZSLU7uluwWQGFJlislvv5jhIa7hLx6wwNbNm34J5lEpA0pU57n/NocYCKwavivg4DCTGRNnzClD9LxqkJVaBUz7YbaQnfUgX4LoNZtaQtZ3/oMzXzR0nWsxLTeWDH0Cu1L4yWZsgWqPS0g/g5RNK26o3A/bZ2EfKQfb21yg3kQuPNB38VolIpl77JHuOGgdUxOMekZ03TrpRj1aW9UnDiUUIlAqNnKO59ipmu2vnTN6vHZM1m2Wbc5wuy05BCDPf19QPsOnVB5mJ/KDK2MRUaT1pHzWuAK4l6NxopijX8o93zWtAanq8osAShfhyn7pg6xt8HVkcLJ2UTkluxenhlBGBh0zrmWr7WsHH5R3PZIeze0NKuUj644J9/PClRkOPEcPfdZn+BLKSaeWfjKEnASKMZ5N2Oo0CI0R2K6kqs7xC4a8eZVOrcl3QB8YpZzvIWrSCc66JMaEbWT+vYqc3v/7DBUQkUrxzmx5yBDclSQmnDop7Ifb3TmKUZcFyrYPIbNuUMbTEG3S0Fuweez6tFgpILbQxr7K4pNL9MIr9jcdT,iv:o7AsmTHkz8aF014whkNo0EzWf0dWw1mKju18PoL3em8=,tag:vOwuPw+wToFggvE7/pMDNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEhCRUt1TUpLaHc0R1Jt
            ZnJnZFhwNDRaTStmRnI0NW5IMEdtVG9mVFRzCkxVVVlUMFMxQW1uR0YwOU1oT0gv
            NU5QTlAxWTNjcXprSDdVTnVuN2hnbEkKLS0tIFNXMTc5OTcwRldWUlc1eWpVNkJp
            c2xNV1BTTXdGc0U4dS9VMlNlSDhLWm8K+q3W5N1U//iw9oXF0N5nOGzE7tlQobJr
            Qi6+y+VUUoE0Mk3uYaE81gMm+wfn4Ad1oa6dyIeeKdHFilQozUxsHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T23:07:14Z"
    mac: ENC[AES256_GCM,data:CXKqJWEKnPfJ4V50Bw/rJIe/YxbXaPZ1zOUJI/+OWOu3M28ZQupVP8BlY2je0L1zvNTVyVfVH/VTB/afW9IZag0CSdvpVjgRcsOLlqyVTqy/qdoeLn2go/BKDA/kYdNunXng2E9/z+on4EEHyW7cuAYVR1tt1SicjskmA6JbqN4=,iv:5s2ULFx60txdMx8HxKY/VbmxgocDLrHChkSiZbADN6I=,tag:U6plqb0foG3ZnseTvLYayg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:vObdxDth88C7mjNhHa/wlkQ/K8F8tUjGeiVUp0xpBIKCwK3i5Ll4OAlUACFgCqc/F38JgPQTCS7xkJR33wNf1vsU/PuPsT8B/WhbieNGvEYtnnanG4G9oSXNwI0zaH7TP2nYqSRMQ4vCbNsZ5Xd4oww9Vnx+oZarDHbeeBmOq0cFyOKIU0rn6MwzmNbTuJRQkzhptuGTAZInXE+IEJFbWJiNy+CuVazwsWUOZZocjrXKldxqRK4SOeG/Ci/nCslPiy4+eyZIZKmH1jobDuMu/ortyVL5OmGOyYPet+uj/ClDceKnzBTjIWBSJxvJEXII+KXGn8xQV5jE20UeVXbRVvTZY67cFqZ01Kh5Y4dgY7dqoLovJRnn/LtYFMLjiTbDtfL0e+X9uOeqWCdB7ikrPgM6D/S3vVA/itz3VQ4MgKPes+vSCuLp91amtFJgV8WhVLdzWlcge2poUNPXcrQfooZOpthJAZUgqZlftnP6szjfSn5O+kfdxjJt0maadu8MW5KrtCc89JU26tFqFGso+E+6ZOqAo7jhfFKpJDD0punNKP2BOB25ZyuM+o3pwjqTmaOFtCQg9jxE76fcVSocgwgxWCzlEdG/fK3Um0v4bPDgABKbJRD9+K1xbbPbvD9LbRXqsZv7lixOZJDz3OpDYOEr6w2zvPfBk3I7VXbW+WWjIdUV8o+HygxIsMV5fES7ZwhmqZPGWRhgEORzbaAyx7JRMcJGHZwIJ/98yLlZc7OByKTW2vTODk7JYQ/sc8m7HnLM3BZNNObN63M6S545xuHHL4a+irERk58CUOCiJVOyuoeHjjOJ2qI7TKQVKNvEfoRmxnCx9KZC7tBKUd8ScY/R6rnui94h/yJbNpxhJvqDqmQ7eifb7QfMqf8fhqvdw9YQBPA6fPKtwltVEWpr6rpWjm6YAieQUoo=,iv:loOTo+sq07onhbTEZywQsiEvxfKiYYslYF3fuGkAV+A=,tag:e+edk4FIx/wNcvO8X+Nhyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEhCRUt1TUpLaHc0R1Jt
            ZnJnZFhwNDRaTStmRnI0NW5IMEdtVG9mVFRzCkxVVVlUMFMxQW1uR0YwOU1oT0gv
            NU5QTlAxWTNjcXprSDdVTnVuN2hnbEkKLS0tIFNXMTc5OTcwRldWUlc1eWpVNkJp
            c2xNV1BTTXdGc0U4dS9VMlNlSDhLWm8K+q3W5N1U//iw9oXF0N5nOGzE7tlQobJr
            Qi6+y+VUUoE0Mk3uYaE81gMm+wfn4Ad1oa6dyIeeKdHFilQozUxsHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T23:07:14Z"
    mac: ENC[AES256_GCM,data:CXKqJWEKnPfJ4V50Bw/rJIe/YxbXaPZ1zOUJI/+OWOu3M28ZQupVP8BlY2je0L1zvNTVyVfVH/VTB/afW9IZag0CSdvpVjgRcsOLlqyVTqy/qdoeLn2go/BKDA/kYdNunXng2E9/z+on4EEHyW7cuAYVR1tt1SicjskmA6JbqN4=,iv:5s2ULFx60txdMx8HxKY/VbmxgocDLrHChkSiZbADN6I=,tag:U6plqb0foG3ZnseTvLYayg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
