apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:bg18/JDNEB2s9p4SiTIsWeFq8YrkaxYaKJ5Y91nzH/26k0omU9yxrGiWWo9oTg4zrBK9GRxv/GnUsO5bvZbJdFzNsoW9pOO/hu6sJbKd7pK9hxA1Awk0n84upMx2lwq/OKsySFZQmbQamcMATrv54t6RbUpxhPaiSeZ0pJrf+qSboA2gNpW0dHAQEYCBO8VrR1Cpt1hA5P54TdHLrdjqUnZwGty8zUScYdBeQ5teoKJqaB6qwC8d4/zhjE0RU0SGl36UBMcwEjHWlsjh4UuIxgx8QsJKjKSglIaeB6kfYI1JrlTaxw/RQzyXZawwE/WsMuufdSvXTN/5CeNuPt9XrtXSlVscm0a6wC7Cr9SpbPQQmPul+9FXfHo6jfdbT4Q+e3vOxFJLwaA+zgt7Hls3w8lYCB8UTO1f7+e/d9RVQ5OLeqL5u87EGv5Nj1ktuoCf3DHS/Q3K9MHn5tcSGBe22Q1A/07wS6OMdITg6RmeFLpJUT8ZpZ3h43vqC9Sj8Th4+v8I1Fla2bXvJxrVvTN2JJco/zUjIdopXOD5JEhWf1PDdns8Qpc6SkGct1owlV/+68MLqUpzkTQ23D4HvGiA2D+9sw+yFs4yAzi5xz2vQNXe+xNFPZgtyUJHMw5jRocBtH6NR7XNoeuAvtckW57Qyo3+B++kCEsYSmCJ6e3/8jPSN8Pyu6ZV+gnuiRsth0oaV8lYUHn1nDCR/Rfoe7WeLD0w0N9B1RZMVikKK6GkwipdUMl4XijnvGDt3X48WBg2va7V19SEsyghJ+PKp2wFN5XEIF5Wh6BWLmTHyMzEHz09yEZTP4+n+DPhTT7sCrW+mDq8E1w0E3xF+g9QlmrubsjYUxJg7THoDeZ7bc0c8MALzfp7M6kpwUC6vtZLKYZ3kYAe3+kYpEYtp1tQkUd4njSUuKtj1i4LTf4BNgUFESYaFzoMMpLoazmaT4O50tuHzTAprpG8yH1UMJbt87/2l7AcNLXEjJWFif5Fk5I5lH8eHIMT8MX0zUxcjDq3xBteY1tN4BPhF8h7sIUGj5xaK6vjH9Cjrdb5AO+aFMbY39K6qLvZ0m2krmaIq6H/y0Dd/y6ybV3MQBZLrjzhbcAE7gJQuqilW8F9FWZfa47M0MeQBK4rcvNzktm8DTrhP/z49T9n6+eTOn2kmFwc21auneVD88EzhqjvEboEakCKWbzEyDh41UO3azGWWuQS5mwy5Uq9GRFSK2Ei1zvgndWAVBa0E43qFaiNmLa8tBAT21uTDH0h6iOZ1l0XqJsgx5ngap+Vhx3Rxeus2MqIITxW9UvUUIaMaOYFciWAh/+CTmwvnktnYK5JzxkVqLt7nGzIr7+d4u0eaaoPIr4WFswusbfLuEKRUzfPV1E/reSPnipZYYrpTEaEjdzuh9Vh+rDngRu7+IHyz2Bbws2u6PJnHLnms1g1YtkGXFh8qjgbn7y37loIERFF,iv:wc3myqVoTkqy5/TcdtQObEYopzqXzuTAIxYUQ1gQCJ8=,tag:BV+ipMOdWTw5peEOwKmc5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEhCRUt1TUpLaHc0R1Jt
            ZnJnZFhwNDRaTStmRnI0NW5IMEdtVG9mVFRzCkxVVVlUMFMxQW1uR0YwOU1oT0gv
            NU5QTlAxWTNjcXprSDdVTnVuN2hnbEkKLS0tIFNXMTc5OTcwRldWUlc1eWpVNkJp
            c2xNV1BTTXdGc0U4dS9VMlNlSDhLWm8K+q3W5N1U//iw9oXF0N5nOGzE7tlQobJr
            Qi6+y+VUUoE0Mk3uYaE81gMm+wfn4Ad1oa6dyIeeKdHFilQozUxsHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T23:03:23Z"
    mac: ENC[AES256_GCM,data:owUG6yB1qbRWkD6NwS9+yHrDm4jbETfR/wLufDoLvgNAkz8Y07JSpnzdIvuEyCUeQELyJpwwMI9mLBJ0x5TqLerouceY2cZGBKJrBNWCwsMULdK8klE7eUFXYbKg0hcuAgTuV/hpXvaPdgwB0jwnuoEHDfFfMk7GFAZ23HEZhQY=,iv:q9GIWYje0X5fMGe88TPQrK6nOsbanh1vysI9iBqtC0g=,tag:ASvAyKTvwOFjNRnT3b8b1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:vObdxDth88C7mjNhHa/wlkQ/K8F8tUjGeiVUp0xpBIKCwK3i5Ll4OAlUACFgCqc/F38JgPQTCS7xkJR33wNf1vsU/PuPsT8B/WhbieNGvEYtnnanG4G9oSXNwI0zaH7TP2nYqSRMQ4vCbNsZ5Xd4oww9Vnx+oZarDHbeeBmOq0cFyOKIU0rn6MwzmNbTuJRQkzhptuGTAZInXE+IEJFbWJiNy+CuVazwsWUOZZocjrXKldxqRK4SOeG/Ci/nCslPiy4+eyZIZKmH1jobDuMu/ortyVL5OmGOyYPet+uj/ClDceKnzBTjIWBSJxvJEXII+KXGn8xQV5jE20UeVXbRVvTZY67cFqZ01Kh5Y4dgY7dqoLovJRnn/LtYFMLjiTbDtfL0e+X9uOeqWCdB7ikrPgM6D/S3vVA/itz3VQ4MgKPes+vSCuLp91amtFJgV8WhVLdzWlcge2poUNPXcrQfooZOpthJAZUgqZlftnP6szjfSn5O+kfdxjJt0maadu8MW5KrtCc89JU26tFqFGso+E+6ZOqAo7jhfFKpJDD0punNKP2BOB25ZyuM+o3pwjqTmaOFtCQg9jxE76fcVSocgwgxWCzlEdG/fK3Um0v4bPDgABKbJRD9+K1xbbPbvD9LbRXqsZv7lixOZJDz3OpDYOEr6w2zvPfBk3I7VXbW+WWjIdUV8o+HygxIsMV5fES7ZwhmqZPGWRhgEORzbaAyx7JRMcJGHZwIJ/98yLlZc7OByKTW2vTODk7JYQ/sc8m7HnLM3BZNNObN63M6S545xuHHL4a+irERk58CUOCiJVOyuoeHjjOJ2qI7TKQVKNvEfoRmxnCx9KZC7tBKUd8ScY/R6rnui94h/yJbNpxhJvqDqmQ7eifb7QfMqf8fhqvdw9YQBPA6fPKtwltVEWpr6rpWjm6YAieQUoo=,iv:loOTo+sq07onhbTEZywQsiEvxfKiYYslYF3fuGkAV+A=,tag:e+edk4FIx/wNcvO8X+Nhyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SEhCRUt1TUpLaHc0R1Jt
            ZnJnZFhwNDRaTStmRnI0NW5IMEdtVG9mVFRzCkxVVVlUMFMxQW1uR0YwOU1oT0gv
            NU5QTlAxWTNjcXprSDdVTnVuN2hnbEkKLS0tIFNXMTc5OTcwRldWUlc1eWpVNkJp
            c2xNV1BTTXdGc0U4dS9VMlNlSDhLWm8K+q3W5N1U//iw9oXF0N5nOGzE7tlQobJr
            Qi6+y+VUUoE0Mk3uYaE81gMm+wfn4Ad1oa6dyIeeKdHFilQozUxsHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T23:03:23Z"
    mac: ENC[AES256_GCM,data:owUG6yB1qbRWkD6NwS9+yHrDm4jbETfR/wLufDoLvgNAkz8Y07JSpnzdIvuEyCUeQELyJpwwMI9mLBJ0x5TqLerouceY2cZGBKJrBNWCwsMULdK8klE7eUFXYbKg0hcuAgTuV/hpXvaPdgwB0jwnuoEHDfFfMk7GFAZ23HEZhQY=,iv:q9GIWYje0X5fMGe88TPQrK6nOsbanh1vysI9iBqtC0g=,tag:ASvAyKTvwOFjNRnT3b8b1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
