apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TESLAMATE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:lmkOVkyBu8u+CqV8PCNdBw==,iv:VC8skSjFu4qhsEZiuSfIHApgSzJXL1vnGopGVhvXr9A=,tag:XuCT3WNysxOnP9uZ5n3ESw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbStsdlVwZFhjaURZcGty
            R2FwQkFyTHpsZ1IzZjBZelVTc09rZHpGNlRFCms5cUp4ejJXbEM1M1lMSEo0TWxn
            VkZzRk5tN1NFMVZ6eVlGTFoxNTVmSkUKLS0tIFZnRkNITlZHb1BwRlhzeUM3SXdV
            eTdTd0d4cDdLNDRDYmM2elNObXBrWW8KFG9Y1mEen8moIte3fQtXMTKF+q/Zge5o
            65fx0y/DlPOL5ruivPJy679qY0YoaICq/pQ3/SHq7X3NAv32fAbvGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-15T18:35:47Z"
    mac: ENC[AES256_GCM,data:1XBieyIZd8mE6tsFtXanxz8+BNf/+OlaXthfYUJQsk3B5EutytIk68UWcRsboM7zZWrVZWvby83I40MH8OgbxOim7evOrbOb/I63NxmEcQiqAms3LPT5a6hmZN1FrUOsigBFx8156WGNHESnIv+3P0QgBlBw2qgEFjYtK54bFU0=,iv:xsyO2QzQHqoCvEcX86SzgRU3fy3cLkVkFKZ/xRLXkEI=,tag:pkAIxyrv1a+BMzmyrgszTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
