---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscan
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: cloudb0x/autoscan
      tag: master

    env:
      PUID: 568
      PGID: 100

    service:
      main:
        ports:
          http:
            port: 3030

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        type: configMap
        name: autoscan-config
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true

    resources:
      requests:
        cpu: 15m
        memory: 226M
      limits:
        memory: 1937M
