---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autoscan-data
  namespace: downloads
  labels:
    app.kubernetes.io/name: autoscan
    app.kubernetes.io/instance: autoscan
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block
