---
mqtt:
  host: mosquitto.home-automation
  port: 1883
  topic_prefix: frigate
  user: frigate
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: False

# Global objects configuration
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

# Global ffmpeg configuration
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac

# Global rtmp configuration
rtmp:
  enabled: true

# Global snapshots configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7

# Global record configuration
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 7
      mode: active_objects

# Specify camera's
cameras:
  courtyard_porch_doorbell:
    # Camera-specific ffmpeg configuration
    ffmpeg:
      inputs:
        - path: "rtsp://{FRIGATE_CAMERA_COURTYARD_DOORBELL_USER}:{FRIGATE_CAMERA_COURTYARD_DOORBELL_PASSWORD}@{FRIGATE_CAMERA_COURTYARD_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - rtmp
            - record
        - path: "rtsp://{FRIGATE_CAMERA_COURTYARD_DOORBELL_USER}:{FRIGATE_CAMERA_COURTYARD_DOORBELL_PASSWORD}@{FRIGATE_CAMERA_COURTYARD_DOORBELL_HOST}:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect

    # Camera-specific detection configuration
    detect:
      width: 1920
      height: 1080
      fps: 10

    # Camera-specific detection configuration
    motion:
      mask:
        - "1595,0,1920,0,1920,1080,1278,1080,1332,1080,1242,1080,1045,734,1053,0"
        - "0,1080,221,1080,433,921,386,498,0,439"
        - "1032,487,1037,726,843,731,842,492"

    # Camera-specific detection configuration
    objects:
      track:
        - person
      filters:
        person:
          mask: "1595,0,1920,0,1920,1080,1278,1080,1332,1080,1242,1080,1045,734,1053,0"

    # Camera-specific recording configuration
    record:
      events:
        retain:
          default: 14

    # Camera-specific snapshots configuration
    snapshots:
      retain:
        default: 14

  # garage:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://{FRIGATE_CAMERA_GARAGE_USER}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@{FRIGATE_CAMERA_GARAGE_HOST}:554/cam/realmonitor?channel=1&subtype=1
  #         roles:
  #           - rtmp
  #       - path: rtsp://{FRIGATE_CAMERA_GARAGE_USER}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@{FRIGATE_CAMERA_GARAGE_HOST}:554/cam/realmonitor?channel=1&subtype=2
  #         roles:
  #           - detect
  #       - path: rtsp://{FRIGATE_CAMERA_GARAGE_USER}:{FRIGATE_CAMERA_GARAGE_PASSWORD}@{FRIGATE_CAMERA_GARAGE_HOST}:554/cam/realmonitor?channel=1&subtype=0
  #         roles:
  #           - record

  #   # Camera-specific detection configuration
  #   detect:
  #     width: 1920
  #     height: 1080
  #     fps: 10

  #   # Camera-specific recording configuration
  #   record:
  #     events:
  #       retain:
  #         default: 14

  #   # Camera-specific snapshots configuration
  #   snapshots:
  #     retain:
  #       default: 14
