---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amcrest2mqtt-secrets
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: amcrest2mqtt-secrets
    creationPolicy: Owner
  data:
    - secretKey: AMCREST_USERNAME
      remoteRef:
        key: Amcrest Doorbell
        property: courtyard_username
    - secretKey: AMCREST_PASSWORD
      remoteRef:
        key: Amcrest Doorbell
        property: courtyard_password
    - secretKey: MQTT_USERNAME
      remoteRef:
        key: mosquitto
        property: amcrest2mqtt_courtyard_username
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: mosquitto
        property: amcrest2mqtt_courtyard_password
