---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: docker.io/excalidraw/excalidraw
      tag: latest@sha256:40512b1358ecb4d84cf88b8b05d164e36acb7e6569a741cf2a7c82ce16243e27

    service:
      main:
        ports:
          http:
            port: 8080
            targetPort: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/instance: "todd,andy"
          hajimari.io/icon: "mdi:draw-pen"
          external-dns.alpha.kubernetes.io/target: ingress.greyrock.tech
        hosts:
          - host: &host "draw.greyrock.tech"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 128M
