---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-01
spec:
  restartPolicy: Never
  nodeName: worker-01
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-02
spec:
  restartPolicy: Never
  nodeName: worker-02
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-03
spec:
  restartPolicy: Never
  nodeName: worker-03
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-04
spec:
  restartPolicy: Never
  nodeName: worker-04
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-05
spec:
  restartPolicy: Never
  nodeName: worker-05
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-06
spec:
  restartPolicy: Never
  nodeName: worker-06
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-07
spec:
  restartPolicy: Never
  nodeName: worker-07
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-08
spec:
  restartPolicy: Never
  nodeName: worker-08
  containers:
    - name: disk-wipe
      image: busybox@sha256:7b3ccabffc97de872a30dfd234fd972a66d247c8cfc69b0550f276481852627c
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
          "blkdiscard /dev/sda",
        ]
