---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-01
spec:
  restartPolicy: Never
  nodeName: worker-01
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-02
spec:
  restartPolicy: Never
  nodeName: worker-02
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-03
spec:
  restartPolicy: Never
  nodeName: worker-03
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-04
spec:
  restartPolicy: Never
  nodeName: worker-04
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-05
spec:
  restartPolicy: Never
  nodeName: worker-05
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-worker-06
spec:
  restartPolicy: Never
  nodeName: worker-06
  containers:
    - name: disk-wipe
      image: quay.io/ceph/ceph:v16.2.10
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "sgdisk -Z /dev/sda",
          "blkdiscard /dev/sda",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sda",
        ]
