# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  cloud {
    organization = "grey-rock"
    hostname     = "app.terraform.io"
    workspaces {
      name = "greyrock-s3-provisioner"
    }
  }
}
