---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .azuread_grafana_client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .azuread_grafana_client_secret }}"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .azuread_grafana_authorization_endpoint }}"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .azuread_grafana_token_endpoint }}"
  dataFrom:
    - extract:
        key: auth0
      rewrite:
        - regexp:
            source: "(.*)"
            target: "auth0_$1"
