---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.343@sha256:b5abad87e53dbe73ebff66e3d93a78ad88616fef4224476d03a3eecc37dae62a

    podAnnotations:
      secret.reloader.stakater.com/reload: sonarr-secrets

    podSecurityContext:
      supplementalGroups:
        - 65539
        - 100

    env:
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: "https://sonarr.greyrock.tech"
      SONARR__LOG_LEVEL: info
      SONARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sonarr-secrets
            key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "sonarr.greyrock.tech"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        type: nfs
        server: "nas01.private.greyrock.io"
        path: /mnt/user/media
        mountPath: /data/nas-media

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
