---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kyverno
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/system/kyverno/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-policies
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/system/kyverno/policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-kyverno
