---
- hosts: nas

  gather_facts: true
  any_errors_fatal: true

  remote_user: todd
  become: yes

  tasks:
    - name: "role: update"
      ansible.builtin.import_role:
        name: update.nas
      tags: update
