---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-ddns-secrets
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: Cloudflare
        property: cloudflare-ddns
    - secretKey: apprise-discord-webhook
      remoteRef:
        key: Cloudflare
        property: cloudflare-ddns-discord-webhook
