---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-ddns
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: hotio/cloudflareddns
      tag: latest

    env:
      - name: CF_HOSTS
        value: ingress.greyrock.tech
      - name: CF_ZONES
        valueFrom:
          secretKeyRef:
            name: cloudflare-ddns-secrets
            key: cloudflare_zones
      - name: CF_APITOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-ddns-secrets
            key: cloudflare_api_token
      - name: CF_RECORDTYPES
        value: A
      - name: APPRISE
        valueFrom:
          secretKeyRef:
            name: cloudflare-ddns-secrets
            key: apprise-discord-webhook
      - name: LOGLEVEL
        value: "2"
      - name: INTERVAL
        value: "300"

    service:
      main:
        enabled: false

    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi
