---
ansible_host: '172.16.30.7'
ansible_python_interpreter: /usr/bin/python3
ansible_user: todd

#zfs setup
zfs_install_update: false
zfs_enable_nfs: true
zfs_manage_filesystem_permissions: true
zfs_enable_samba: false
zfs_enable_performance_tuning: false # Not idempotent
zfs_create_pools: true
zfs_create_filesystems: true
zfs_monitoring_capacity_threshold: 92
zfs_pools:
  - name: 'tank'
    action: 'create'
    atime: 'off'
    ashift: 12
    xattr: sa
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LHZ4GAG'
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_QGKAHABT'
    type: 'mirror'
    state: 'present'
  - name: 'tank'
    action: 'add'
    atime: 'off'
    ashift: 12
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL522402DA800RGN'
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL52240391800RGN'
    type: 'cache'
    state: 'present'
zfs_filesystems:
  - name: series
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/series/
  - name: movies
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/movies/
  - name: music
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/music/
  - name: backup
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/backup/
  - name: downloads
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/downloads/
  - name: media
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/media/
  - name: photos
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/photos/
  - name: software
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/software/
  - name: documents
    pool: tank
    state: present
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/documents/
  - name: frigate
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/frigate/
  - name: minio
    pool: tank
    state: present
    owner: 1000
    group: 1000
    mountpoint: /tank/minio/
  - name: books
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/books/
  - name: unsorted
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/unsorted/
  - name: syncthing
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/syncthing/

zfs_enable_monitoring: true
zfs_monitoring_scrub_max_age: 8
zfs_pools_scrub_cron:
  minute: 0
  hour: 2
  day: '*'
  month: '28'
  weekday: '*'
