---
clusterName: greyrock-ops

talosVersion: v1.3.1
kubernetesVersion: 1.26.0
endpoint: "https://greyrock-ops.private.greyrock.io:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - greyrock-ops.private.greyrock.io

nodes:
  - hostname: control-01.private.greyrock.io
    ipAddress: 172.16.30.101
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: ${clusterEndpointIP}
  - hostname: control-02.private.greyrock.io
    ipAddress: 172.16.30.102
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: ${clusterEndpointIP}
  - hostname: control-03.private.greyrock.io
    ipAddress: 172.16.30.103
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: ${clusterEndpointIP}
  - hostname: worker-01.private.greyrock.io
    ipAddress: 172.16.30.104
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.104/24
  - hostname: worker-02.private.greyrock.io
    ipAddress: 172.16.30.105
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.105/24
  - hostname: worker-03.private.greyrock.io
    ipAddress: 172.16.30.106
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.106/24
  - hostname: worker-04.private.greyrock.io
    ipAddress: 172.16.30.107
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.107/24
  - hostname: worker-05.private.greyrock.io
    ipAddress: 172.16.30.108
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.108/24
  - hostname: worker-06.private.greyrock.io
    ipAddress: 172.16.30.109
    controlPlane: false
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 10
            dhcp: false
            addresses:
              - 172.16.10.109/24

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: false
        apiServer:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
            oidc-client-id: ${oidcClientId}
            oidc-groups-claim: groups
            oidc-groups-prefix: 'oidc:'
            oidc-issuer-url: ${oidcIssuerURL}
            oidc-username-claim: email
            oidc-username-prefix: 'oidc:'
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        extraManifests:
          - https://raw.githubusercontent.com/Doonga/greyrock-ops/main/infrastructure/talos/greyrock-ops/rbac/oidc.yaml

      machine:
        files:
          - content: |
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
          nodeIP:
            validSubnets:
              - 172.16.30.0/24
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.greyrock.tech:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.greyrock.tech:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - greyrock-ops.private.greyrock.io
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 172.16.30.2
        registries:
          config:
            docker.io:
              auth:
                username: ${dockerHubUsername}
                password: ${dockerHubPassword}
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

worker:
  patches:
    - |-
      machine:
        files:
          - content: |
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
          nodeIP:
            validSubnets:
              - 172.16.30.0/24
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.greyrock.tech:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.greyrock.tech:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - greyrock-ops.private.greyrock.io
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 172.16.30.2
        registries:
          config:
            docker.io:
              auth:
                username: ${dockerHubUsername}
                password: ${dockerHubPassword}
