clusterEndpointIP: ENC[AES256_GCM,data:CVTQ6NFW3A3SBMjQ,iv:wVHxdLE88NaWzCw1YjAkMZ6k0HlUvv+RXkdxRhB9co4=,tag:W5y6yEkRB7Un4W63JWGfew==,type:str]
oidcClientId: ENC[AES256_GCM,data:agD1iGRcD2579wbGIiUiHJk2UquoBTO7NkYiiuP+I0E=,iv:kkt2rR9bVhFlBkDyxDDMwGTDaZe7NmvwnenAqTJXusM=,tag:NoPbOQKpYDXJU2Ccj0Laag==,type:str]
oidcIssuerURL: ENC[AES256_GCM,data:KVgHAMAXlT5JO/1gc1qYEZE2qahOcWj4Bjs=,iv:4SECqubha2Gs6ReeHH3OxIucXMk9F6fQAq0PkecqhcA=,tag:BDiH/X5pfB6n53CsMFU6kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2xKQUVCMzd6bWFXMExQ
            ZE9iemkycnFOMVJTYlg2S051SjBWTTRvN2lZCmU1YWluTWdOZGtPbGtVQnk2K2R2
            ZWcvU2xpRkxRTFVwR1hJSGJ5UGFrVHcKLS0tIFNmY2g2eVdDVWk5L3h3SXAyMHc2
            eEtpdHNQYkorQmxsQUcwV3p3eDU1Y0EKIAAjybQn+st4wViNO2HDZnTDN4zsR9yY
            XbukoArjeFsHBi/K2UOSyglI+G3cyPFe1dMUAW2sMnW3Vgb7kh9rdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T21:13:38Z"
    mac: ENC[AES256_GCM,data:hZk24YD0Ak4w2Lw6dX5/ZHvQ8enkyyyxidAQsrlKUv2LQq2xZzDXMWTu2QOYDnUKHbjldAXjAatB6Ud/9gcepKQfNPp1qXgwqeN3vXxuOnU0jpKf5f6fUhnLghkKM4nQt1+2/VkQM9npzoHNqwOVe9XSHPeSSpg/LZeOElyuBA8=,iv:MZqqqqO0zN4H0sy98KVqR6ShuJ6einE+aQJSRwdpjBg=,tag:ihgzlzRCRKOTNJYKK/YmNQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
