clusterEndpointIP: ENC[AES256_GCM,data:CVTQ6NFW3A3SBMjQ,iv:wVHxdLE88NaWzCw1YjAkMZ6k0HlUvv+RXkdxRhB9co4=,tag:W5y6yEkRB7Un4W63JWGfew==,type:str]
oidcClientID: ENC[AES256_GCM,data:1o1Z0MQZ9nzPINoRbTgh4Gj9YR9nkwpOSHWlzS03VS+HlLII,iv:QtJR5KI6+AlDyzoZevNH9k2sDtlucScgueCqe+9hcYQ=,tag:pma9nMuKKkBD1YhzHpezXw==,type:str]
oidcIssuerURL: ENC[AES256_GCM,data:EVaIN7d42KgxeccCtc91e6YBPlFMMPdUXC/Kfpv9Uv+BQvLuj8p07X3gcePgbNv1D4ggzR5PbfqGv6Uw1VwjnL3itObI9er0SUix2y59wqt/+Q==,iv:GgdQAgXDqrNifZ7KO6tzItKFfA0UP9uupMwrFlkFfF0=,tag:uSuzEXppvwOVzZoV4kNacw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age136uhfkdjvxacd40d9r7guay8a7tqdz9y0264xvxvhvswxwh229lqlwan93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ2xKQUVCMzd6bWFXMExQ
            ZE9iemkycnFOMVJTYlg2S051SjBWTTRvN2lZCmU1YWluTWdOZGtPbGtVQnk2K2R2
            ZWcvU2xpRkxRTFVwR1hJSGJ5UGFrVHcKLS0tIFNmY2g2eVdDVWk5L3h3SXAyMHc2
            eEtpdHNQYkorQmxsQUcwV3p3eDU1Y0EKIAAjybQn+st4wViNO2HDZnTDN4zsR9yY
            XbukoArjeFsHBi/K2UOSyglI+G3cyPFe1dMUAW2sMnW3Vgb7kh9rdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T18:53:09Z"
    mac: ENC[AES256_GCM,data:enfmIP0NpyThlYsLKvz4S1DvtulsMe3SgneGDuWPn82pa1bdoYpFtML4Vh30UlKu8sJXpeyhzp5xQMq1jz+h4l3+ZYyti/2ydeVreLkrGQgS3McwAFyZo/7aXAu/HcNHLtI0ZXpyROcMgDmPMnZCai5Fj+lIjuLvPrhzzs9Ms4U=,iv:mne2t9/10k891WsobwPRcCo+nGu/BOGy5DvfyQcH7gk=,tag:JZwpFytjJnLgivAXawyHaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
