---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hajimari-todd
  namespace: selfhosted
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1

    hajimari:
      defaultEnable: false
      darkTheme: chalk
      instanceName: "todd"
      title: "Todd"
      namespaceSelector:
        matchNames:
          - default
          - network
          - selfhosted
          - downloads
          - home-automation
          - monitoring
          - media
          - rook-ceph
      name: "Captain"
      customApps:
        - name: Camelus-Plexii
          url: http://10.1.0.50:5000
          icon: test-tube
        - name: Discord Server
          url: "https://discord.gg/blah"
          icon: discord
        - name: Tyg3r Blog Admin Panel
          url: "https://tyg3r.blah"
          icon: post
      bookmarkGroups:
        - group: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
        - group: Cloud
          links:
            - name: Drive
              url: "https://drive.google.com"
        - group: Design
          links:
            - name: Awwwards
              url: "https://awwwards.com"
            - name: Dribbble
              url: "https://dribbble.com"
            - name: Muz.li
              url: "https://medium.muz.li/"
        - group: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - group: Lifestyle
          links:
            - name: Design Milk
              url: "https://design-milk.com/category/interior-design/"
            - name: Dwell
              url: "https://www.dwell.com/"
            - name: Freshome
              url: "https://www.mymove.com/freshome/"
        - group: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: Trakt
              url: "http://trakt.tv"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - group: Reading
          links:
            - name: Instapaper
              url: "https://www.instapaper.com/u"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - group: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/instance: "todd"
          hajimari.io/icon: "weather-sunset"
        hosts:
          - host: &host "home-todd.greyrock.tech"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config-todd
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-todd-settings

    resources:
      requests:
        cpu: 100m
        memory: 128M
