---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config-todd
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block
