---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: selfhosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      replicas: 3
      strategy: RollingUpdate

    image:
      repository: ghcr.io/auricom/libreddit
      tag: 0.29.1@sha256:b241f1f55fc3a05a081967bbdf2fa4a9246f96c2a821b00811b139718e4874fd

    env:
      LIBREDDIT_DEFAULT_SHOW_NSFW: true
      LIBREDDIT_DEFAULT_WIDE: true

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/auth-url: https://auth.greyrock.tech/oauth2/auth?allowed_groups=libreddit
          nginx.ingress.kubernetes.io/auth-signin: https://auth.greyrock.tech/oauth2/start?rd=$scheme://$best_http_host$request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-email, x-auth-request-groups"
          hajimari.io/enable: "true"
          hajimari.io/instance: "todd,andy"
          hajimari.io/icon: simple-icons:reddit
        hosts:
          - host: &host 'libreddit.greyrock.tech'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: libreddit

    podAnnotations:
      setGateway: 'true'

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /settings
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes

      startup:
        enabled: false

    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 250Mi
