---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
    - # Google Coral USB Accelerator
      name: google.coral
      labels:
        google.feature.node.kubernetes.io/coral: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["1a6e", "18d1"] }
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rtlamr-device
spec:
  rules:
    - # RTLAMR radio
      name: rtlamr
      labels:
        rtlamr.feature.node.kubernetes.io/rtlamr: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["0bda", "2838"] }
