---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-hajimari-todd
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/greyrock-ops/apps/selfhosted/hajimari-todd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: hajimari
      namespace: selfhosted
  interval: 30m
  retryInterval: 1m
  timeout: 3m
