---
name: Meta - Enforce PR labels

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-label:
    name: Enforce PR labels
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: "do-not-merge"
