---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./garage-nas.yaml
  - ./node-exporter-gateway.yaml
  - ./pikvm-node-exporter.yaml
  - ./speedtest-exporter-gateway.yaml
