---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: nitter-redis
  app.kubernetes.io/instance: nitter
